"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username \
$directory \
$git_branch \
[󰁔](bold green) \
"""

add_newline = false

[directory]
format = "[$path](cyan)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[$symbol $branch](bold green)"
symbol = ""

[username]
disabled = false
format = "[$user](bright-purple)"
show_always = true
