"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status \
[#](white) \
"""

add_newline = false

[directory]
format = "[ $path ](bright-white)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[ $symbol $branch ](bold green)"
symbol = ""

[git_status]
disabled = false
format = '[$all_status$ahead_behind](bold cyan)'
up_to_date = '[ ✓ ](bright purple)'
untracked = '[?\($count\)](bright-yellow)'
stashed = '[\$](bright-purple)'
modified = '[!\($count\)](bright-yellow)'
renamed = '[»\($count\)](bright-purple)'
deleted = '[✘\($count\)](bright-red)'
staged = '[++\($count\)](bright-yellow)'
ahead = '[⇡\(${count}\)](bright-cyan)'
behind = '[⇣\(${count}\)](bright-red)'
diverged = '⇕[\[](bright-purple)[⇡\(${ahead_count}\)](bright-cyan)[⇣\(${behind_count}\)](red)[\]](bold magenta)'

[username]
disabled = false
format = "[$user](bright-purple)"
show_always = true
